chrc:
  valid: ' !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  normal: '`1234'
  shift: ''
fld_sty:  # field style
  nd_pad: 2
  nd_sz: 10
cursor:
  width: 2
  ofsx: 0  # offset-x of the cursor (relative)
  ofsy: -15  # offset-y of the cursor (relative)
  limit: 15  # cursor counter limit; updates per frame
  cooldown: 30  # frames before to start the continuous press
file_cfg:
  project: project.yaml
  settings: settings.yaml
  skeleton: skeleton.dat.bin
  parameterize: param.dat.bin
  delimeter:
    inp: "\x01"
    out: "\x02"
    cns: "\x03"
    spc: "\x00"
    spr: "\x04"
file_index:
  MySampleProject: 'C:/Users/Andrew Shen/Desktop/ProjectEmerald'